spring:
  application:
    name: hello-concurrent-control
  datasource:
    url: jdbc:mysql://localhost:3306/mydatabase
    username: myuser
    password: secret
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
  rabbitmq:
    host: localhost
    port: 5672
    username: myuser
    password: secret
    template:
      reply-timeout: 5000
      default-receive-queue: reply-queue

management:
  endpoints:
    web:
      exposure:
        include: "*"
